export const projectsData = [
  {
    title: "Techjeeva",
    description: "Explore various funding schemes and access all the information you need in one place.",
    image: "/images/techjeeva.png",
    web: "https://findfund.vercel.app/",
    git: "https://github.com/jjf2009/FIIRE",
    category: "web",
    categoryName: "Web App",
    technologies: ["React", "Javascript", "Googlesheet", "Google APP Script"],
  },
  {
    title: "Ride Buddy",
    description: "Carpooling Website for GEC Students",
    image: "/images/Ridebuddy.png",
    web: "https://ridebuddy-8p6s.onrender.com/",
    git: "https://github.com/jjf2009?tab=repositories",
    category: "web",
    categoryName: "Web App",
    technologies: ["React", "Node.js", "Express", "MongoDB"],
  },
  {
    title: "OpenCV Projects",
    description: "OpenCV Projects Using Mediapipe and YOLO",
    image: "/images/opencv.jpg",
    web: "https://github.com/jjf2009?tab=repositories",
    git: "https://github.com/jjf2009/OpenCV_Projects",
    category: "ai",
    categoryName: "AI",
    technologies: ["Python", "OpenCV", "Mediapipe", "YOLO"],
  },
  {
    title: "Nike Website Clone",
    description: "A clone of the Nike website with responsive design and modern web practices.",
    image: "/images/07.png",
    web: "https://nike-landing-lac.vercel.app/",
    git: "https://github.com/jjf2009/Nike_New",
    category: "web",
    categoryName: "Web App",
    technologies: ["React", "Tailwind CSS", "Vite"],
  },
  {
    title: "Pokedex",
    description: "An interactive Pokedex application built to showcase Pokemon data with responsive design.",
    image: "/images/02.png",
    web: "https://pokedex-rho-lake.vercel.app/",
    git: "https://github.com/jjf2009/PokemonSearchApp",
    category: "web",
    categoryName: "Web App",
    technologies: ["React", "CSS", "Pokemon API"],
  },
  {
    title: "Connect 4",
    description: "A fun Connect 4 game implemented with engaging UI and responsive design.",
    image: "/images/03.png",
    web: "https://connet-4.vercel.app/",
    git: "https://github.com/jjf2009/Connet-4",
    category: "game",
    categoryName: "Game",
    technologies: ["JavaScript", "HTML", "CSS"],
  },
  {
    title: "Country Code Finder",
    description: "A tool to search and find country codes, built with a responsive interface.",
    image: "/images/06.png",
    web: "https://country-search-hackathon.vercel.app/",
    git: "https://github.com/jjf2009/Search-Bar-Hackathon",
    category: "tool",
    categoryName: "Tool",
    technologies: ["React", "CSS", "REST API"],
  },
  {
    title: "Todo App",
    description: "A simple and efficient Todo application to manage tasks with responsive design.",
    image: "/images/04.png",
    web: "https://basic-todo-one.vercel.app/",
    git: "https://github.com/jjf2009/BasicTodo",
    category: "tool",
    categoryName: "Tool",
    technologies: ["React", "CSS", "LocalStorage"],
  },
  {
    title: "Company Registration Portal",
    description: "A portal for registering companies with a user-friendly interface and responsive design.",
    image: "/images/05.png",
    web: "https://companydirectoryportal.vercel.app/",
    git: "https://github.com/jjf2009/CompanyDirectoryPortal.git",
    category: "web",
    categoryName: "Web App",
    technologies: ["React", "CSS", "Firebase"],
  },
  {
    title: "Palindrome Checker",
    description: "An application to check if a word or phrase is a palindrome, featuring responsive design.",
    image: "/images/08.png",
    web: "https://palindrome-checker-chi.vercel.app/",
    git: "https://github.com/jjf2009/Palindrome_Checker",
    category: "tool",
    categoryName: "Tool",
    technologies: ["JavaScript", "HTML", "CSS"],
  },
  {
    title: "Roman Number Converter",
    description: "A tool to convert numbers to Roman numerals, built with a responsive layout.",
    image: "/images/09.png",
    web: "https://roman-number-converter-delta.vercel.app/",
    git: "https://github.com/jjf2009/Roman_Number_Converter-",
    category: "tool",
    categoryName: "Tool",
    technologies: ["JavaScript", "HTML", "CSS"],
  },
  {
    title: "Steve Jobs Tribute",
    description: "A tribute page dedicated to Steve Jobs, showcasing responsive design and modern web principles.",
    image: "../images/01-Tribute.png",
    web: "https://steve-jobs-tribute.vercel.app/",
    git: "https://github.com/jjf2009/Steve_Jobs_Tribute",
    category: "web",
    categoryName: "Web App",
    technologies: ["HTML", "CSS", "Responsive Design"],
  },
]
